### ISSUE TITLE
Confuse how to use this addon in blender ..?

### ISSUE THREAD

**Issue by seemon2** [hoontee/godot-ni-mate-motion-capture#9]
Hi,

I am confuse how to use this file ... is it an "addon" to Blender? If so I don't see any "python" files to install into Blender.
I understand this is a "rig" (armature" setup already that works with Ni Mate addon in armature.
That way, one can use this rig for Blender animation ..  

Cheers.

**Comment by hoontee** [comment]
This addon is for the Godot engine. For the Blender plugin, please visit: https://ni-mate.com/download/

**Comment by seemon2** [comment]
Thanks for the clarification. Will look into the blender addon instead :)
